In [1]:
# numpy useful function

In [2]:
# numpy.all(array, axis, out, keepdims)-check whether all the elements in an array evaluate to True.
# numpy.any(array, axis, out, keepdims)-check whether any of the elemenst in an array evaluate to True
# numpy.place(array, mask, vals) -Makes changes in the array according to the parameters
# numpy.extract(condition, array) - returns elecments from the input array if they satisfied the specific condition
# numpy.take() function returns element from array aling the mentioned axis and indices
# numpy.put() function replaces specific elements of an array with given values of p_array
# numpy.compress() function returns selected slices of an array along mentioned axis that satisfies an axis
# numpy.divide(arr1, arr2); returns the element wise division between two arrays
# numpy.apply_along_axis(fun1, axis, array); returns the function applied array
# numpy.rot90(); returns the rotation of an array by 90 degree in the plane
# numpy.floor_divide(arr1, arr2) -used to divide each element of arr1 to each element of arr2 (floor-division)
# numpy.true_divide(arr1, arr2) -used to divide each element of arr1 to each element of arr2 (true-division)
# numpy.apply_over_axes(func, array, axes): applies a function repeatedly over multiple axes in an array
# numpy.tile()- function constructs a new array by repeating array -arr, the number of times we want to repeat as per repetitions.
# numpy.argmin(array, axis =0) - function returns indices of min element of the array in particular axis
# numpy.armmax(array, axis =0) - function returns the indices of max element of the array in particular axis
# numpy.random.rand(d0)- function return random value of shape d0
# numpy.ravel(array) - function returns contiguous flatten array
# numpy.nanargmin(array) - function returns the min element of array in particular axis ignoring NANs
# numpy.nanargmax(array) - function returns the max element of array in particular axis ignoring NANs
# numpy.isinf() - function test element-wise whether it is +ve or -ve infinity
# numpy.ndarray.flat(index[tuple(int)]) - function is used as 1_D iterator over N-dimensional arrays; It flat the numpy array
# numpy.isrealobj() - function helps to check If array has no complex type or array has a complex number.
# numpy.expm1() - function helps to find exponential of each element of array
# numpy.amax() - function returns the max element of an array or maximum along the axis 
# numpy.amin() - function returns the min element of an array  or minimum along the axis
# numpy.isscalar(num)- function returns true if element is scalar
# numpy.bincount(array) - function returns the counting of each element in an arrray
# numpy.random.shuffle(array) - function shuffle the element of array randomly
# numpy.rint(x) - mathematical function return round elements of the array to the nearest integer
# numpy.isneginf() function tests element wise whether it is negative infinity or not
# numpy.isposinf() - function tests element wise whether it is +ve infinity or not
# numpy.equal(arr1, arr2)-checks the array1 and array2 is equal element wise or not
# numpy.iscomplex(arr)-check the element wise array is complex number or not
# numpy.unequal(arr1, arr2) - checks whether the two array(arr1, arr2) is unequal or not
# numpy.isnam(arr) -check each element of an array is NAN or not
# numpy.insert(array, object, values, axis=None) - used to insert the value along the mentioned axis before the given indices
# numpy.delete(array, object (subarray which will delete), axis=None) - returns the modified array after deleteing
# numpy.append(array, values, axis = None) - append values along the mentioned axis at the end of the array
# numpy.less(x1, x2) - function that checks whether x1 is less the x2 or not. 
# numpy.round(arr1) - function that roundoff the value each element of an array
# numpy.less_equal(x1, x2) - function that checks each element of x1 is less and equal to x2
# numpy.greater(x1, x2) - function that checks each element of x1 is greater than x2
# numpy.greater_equal(x1, x2) - function that check each elements of x1 is greater and equal to x2
# numpy.iscomplexobj() - function check each element of array is complex or not?
# numpy.isreal(array) - function check the each element of an array is real or not?
# numpy.isfinite(array) -function checks each element of an array is finite or not?
# numpy.flip(arr) - function which flips each element of an array
# numpy.fliplr(arr) - function which flips the elements along left-right
# numpy.flipud(arr) -function which flips the elements along up-down side.
# numpy.isfortran(arr)- checks each elements of an array is FORTRAN order in memory
# numpy.triu(arr)-returns a copied array which takes the element of upper part of an arry
# numpy.tril(arr) -returns a copied array which takes the element of lower part of an array
# numpy.tri(no_of_row, no_of_col, k=?) ; k=0 main diagonal, k>0 digonal above main diagonal, k<0 diagonal below main diagonal
# numpy.prod(array, axis=0/1) -returns the product of each elements along axis
# numpy.square(array) - it square each element of an array
# numpy.exp(array) - calculates the exp of each elements of an array
# numpy.exp2(array) -calculates 2**x; where x is each element of an array
# numpy.cbrt(array) - calcualte cube root of each element in an array
# numpy.fix(array) - retruns round elements of an array to the nearest integer toward 0
# numpy.empty([r, c]) - rerturn an array of size (2X4) with random values
# numpy.empty_like(previous_array) - retruns the array with size of prevous array size and same data type
# numpy.absolute(arr) - retrun the array with absolute value of each element
# numpy.hypot() - calculate the hypotenuse of the right angle trianle, given its side and perpendicular. (x1**2+x2**2)
# numpy.zeros(shape,dtype=None) - return an array with zeros
# numpy.ones(shape, dtype=None) -return an array with ones
# numpy.zeros_like(previous_array) - return an array with zeros
# numpy.ones_like(previous) -return an array with the shape of previous array
# numpy.full_like(array, value, dtype=None) - return an array with all the element of 'value'
# numpy.logical_and(arr1, arr2) - return If the elements of arr1 and elements of arr2 are logically 'and'ed
# numpy.logical_not(arr1, arr2) - return if the elements of arr1 and elements of arr2 is 'not'ed
# numpy.logical_xor(arr1, arr2) - return if the element of arr1 and elements of arr2 is 'XoR'ed
# numpy.degrees(arr1) -convert to an array elements into an degrees
# numpy.radians(arr1) - convert to an array elements into an radian
# numpy.array_equal()
# numpy.array_equiv()
# numpy.ceil()
# numpy.floor()

In [3]:
# numpy.arange([start,]stop[,step][dtype]) - returns an array with evenly spaced elements as per interval

import numpy as np
print("\n numpy.arange() function:\n", np.arange(4).reshape(2, 2), "\n")


 numpy.arange() function:
 [[0 1]
 [2 3]] 



In [4]:
print("\n numpy.arange() function:\n", np.arange(4, 10), "\n")


 numpy.arange() function:
 [4 5 6 7 8 9] 



In [5]:
# np.arange(start, stop, interval); It prints the number from 4 to 20 and it has an interval of 3
print("\n numpy.arange() function:\n", np.arange(4, 20, 3))


 numpy.arange() function:
 [ 4  7 10 13 16 19]


In [6]:
arr_a = np.array([1, 2,3], dtype=float)
arr_b = np.array([4, 5, 6], dtype=float)
dot_product_a_b = np.dot(arr_a, arr_b)
print("\nThe dot_product_a_b:", dot_product_a_b)


The dot_product_a_b: 32.0


In [7]:
# numpy.place(input_arr, mask, values)
# input_array - this is array which has to changed.
# mask - the size of input array and the boolean that must have the same size of input_array
# values - to put into the array, based on mask condition it adds only N elements to the array, If in case values in val are smaller than the mast, same value repeated.

import numpy as np
or_arr = np.arange(12).reshape(3, 4)
print("The original array:\n", or_arr)

The original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
# np.place(or_arr(input_array), mask(condition which satify to all), values(which placed in input_array after checking the mask/conditions))
a = np.place(or_arr, or_arr>5, [5, 12, 23])
print("New array:\n", or_arr)

New array:
 [[ 0  1  2  3]
 [ 4  5  5 12]
 [23  5 12 23]]


In [9]:
# numpy.vdot(); used to dotproduct but in flatten array
import numpy as np
a = np.array([[1, 2], [4, 5]], dtype=float)
b = np.array([[3, 4], [6, 7]], dtype= float)
print("The numpy.vdot():", np.vdot(a, b))
print("The numpy.vot():\n", np.dot(a, b))

The numpy.vdot(): 70.0
The numpy.vot():
 [[15. 18.]
 [42. 51.]]


In [10]:
# numpy.extract(input_array,condition) - used to extract the element from an input_array
import numpy as np
input_arr = np.arange(10).reshape(2, 5)

In [11]:
input_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
condition = np.mod(input_arr, 4)!=0
print("The condition is:", condition)

The condition is: [[False  True  True  True False]
 [ True  True  True False  True]]


In [13]:
print(np.extract(input_arr, condition))

[ True  True  True False  True  True  True False  True]


In [14]:
import numpy as np
new_arr = np.array([[5, 6, 2, 7, 1], [4, 9, 2, 9, 3]])
print("\nNew array:\n", new_arr)
print("\nTaking indices\:\n", np.take(new_arr, [0, 4]))
print("\nTaking indices along the column axis:\n",np.take(new_arr, [0, 4], axis=1))
print("\nTaking indices along the row axis:\n",np.take(new_arr, [0, 1], axis=0))


New array:
 [[5 6 2 7 1]
 [4 9 2 9 3]]

Taking indices\:
 [5 1]

Taking indices along the column axis:
 [[5 1]
 [4 3]]

Taking indices along the row axis:
 [[5 6 2 7 1]
 [4 9 2 9 3]]


In [15]:
# np.trunc() use to return the truncated value of each element in array
# the truncated value comes nearest to 0
input_arr = np.array([0.5, 9.0, 4.5, 6.76, 7.89])
print("The truncated array is:", np.trunc(input_arr))

The truncated array is: [0. 9. 4. 6. 7.]


In [16]:
input_arr = np.array([0.9, 9.0, 4.5, 6.76, 7.89])
print("The truncated array is:", np.trunc(input_arr))

The truncated array is: [0. 9. 4. 6. 7.]


In [17]:
# np.put(array, indices, p_array) used to replace the specific elements of an array with the given value
input_array = np.array([1, 2, 3, 3, 4, 5, 5], dtype=float)
np.put(input_array, [0, 4], [10, 10], mode='clip' )
print("The replaced array is:", input_array)

The replaced array is: [10.  2.  3.  3. 10.  5.  5.]


In [18]:
# numpy.compress(condition, array, axis=None, out=None)
input_arr = np.random.random(10).reshape(2, 5)
print("\nInput array:\n", input_arr)
print("Compressed array:\n", np.compress([1, 3], input_arr, axis=None))


Input array:
 [[0.21572533 0.11206156 0.2098307  0.34527106 0.4048616 ]
 [0.23405631 0.70662158 0.66907996 0.06030198 0.55017582]]
Compressed array:
 [0.21572533 0.11206156]


In [19]:
# numpy.divide(arr1, arr2, out=None, where=True, casting='same_kind', order='K', dtype=None)
# arr1, arr2 should have same shape, and arr2 should not contain 0

arr1 = np.array([2, 3, 4, 5, 6], dtype=float)
arr2 = np.array([2, 2, 2, 2, 2], dtype=float)
print("The divided array elements:\n", np.divide(arr1, arr2))
arr2 = np.array([0, 2, 2, 2, 2], dtype=float)
print("The divided array with 0 in elements of array:", np.divide(arr1, arr2))

The divided array elements:
 [1.  1.5 2.  2.5 3. ]
The divided array with 0 in elements of array: [inf 1.5 2.  2.5 3. ]


C:\Users\uib43225\.conda\envs\fusion\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in true_divide
  


In [20]:
# numpy.apply_along_axis(1d_func, axis, *args, **kwargs) - help us to apply a required function to 1D slices of the given array
args =[3, 8]
# *args allow to send non-keyword variable length argument list to the function
a = list(range(*args))
print("Use of args:", a)
# **kwargs()- allows you to pass keyword variable length of argument to a function, used when we handle named argument in the function

def test_kwargs_argument(in1, in2, in3):
    print("in1:", in1)
    print("in2:", in2)
    print("in3:", in3)

kwargs = {"in3": 1, "in2": "No", "in1":"geeks"}
test_kwargs_argument(**kwargs)

Use of args: [3, 4, 5, 6, 7]
in1: geeks
in2: No
in3: 1


In [21]:
def func1(array):
    return array[0]+array[-1]

array = np.arange(10).reshape(2, 5)
print("The initial array is:\n", array)

new_array = np.apply_along_axis(func1, 0, array)
print("The new array axis=0:\n", new_array)

new_array = np.apply_along_axis(func1, 1, array)
print("The new array axis=1:\n", new_array)

new_array = np.apply_along_axis(sorted, 1, array)
print("The new array after using sorted function to axis=1:\n", new_array)

The initial array is:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
The new array axis=0:
 [ 5  7  9 11 13]
The new array axis=1:
 [ 4 14]
The new array after using sorted function to axis=1:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
# numpy.rot90(array, k(no of times to rotate), axes=(0,1 )) method perfroms rotation of an array by 90 degree
import numpy as np
input_arr = np.random.random(10).reshape(2, 5)

print("Rotated array after 2 times:\n", np.rot90(input_arr, 2))
print("Rotated array after 4 times:\n", np.rot90(input_arr, 4))


Rotated array after 2 times:
 [[0.18705219 0.80023001 0.79530215 0.74943089 0.96796631]
 [0.88917934 0.67265927 0.58773703 0.58844153 0.06032712]]
Rotated array after 4 times:
 [[0.06032712 0.58844153 0.58773703 0.67265927 0.88917934]
 [0.96796631 0.74943089 0.79530215 0.80023001 0.18705219]]


In [23]:
# numpy.floor_divide(arr1, arr2)
import numpy as np 
  
# input_array 
arr1 = [2, 6.5, 21, 21, 12] 
arr2 = [2, 3, 4.4, -3.2, 5] 
print ("arr1         : ", arr1) 
print ("arr2         : ", arr2) 
  
# output_array 
out_floor_divide = np.floor_divide(arr1, arr2, dtype=float) 
print ("\nOutput floor_divide array : ", out_floor_divide) 

out_true_divide = np.true_divide(arr1, arr2, dtype=float)
print ("\nOutput true_division array : ", out_true_divide) 

arr1         :  [2, 6.5, 21, 21, 12]
arr2         :  [2, 3, 4.4, -3.2, 5]

Output floor_divide array :  [ 1.  2.  4. -7.  2.]

Output true_division array :  [ 1.          2.16666667  4.77272727 -6.5625      2.4       ]


In [27]:
# numpy.apply_over_axes(func, array,axes)
input_arr = np.random.random(20).reshape(4, 5)
print("The input_array:\n", input_arr)
print("Apply func over axes:", np.apply_over_axes(np.max, input_arr, axes=0))

The input_array:
 [[0.67070586 0.51197767 0.22657068 0.31465612 0.01935131]
 [0.86094606 0.28455427 0.27101833 0.89932245 0.21709136]
 [0.31732105 0.00351784 0.88815471 0.60306628 0.46086385]
 [0.83945121 0.53461411 0.61124924 0.86284337 0.18565765]]
Apply func over axes: [[0.86094606 0.53461411 0.88815471 0.89932245 0.46086385]]


In [28]:
# numpy.tile(arr, repetitions)
import numpy as np
arr1 = np.array([1, 2, 3, 4])
print("New array after tile 2 times:", np.tile(arr1, 2))
arr2 = np.arange(4).reshape(2, 2)
print("The size of arr2:\n", arr2, arr2.shape)
print("New array after tile 3 times:\n", np.tile(arr2, 3),np.tile(arr2, 3).shape )

New array after tile 2 times: [1 2 3 4 1 2 3 4]
The size of arr2:
 [[0 1]
 [2 3]] (2, 2)
New array after tile 3 times:
 [[0 1 0 1 0 1]
 [2 3 2 3 2 3]] (2, 6)


In [29]:
import numpy as np

arr1 = np.random.random(25).reshape(5, 5)
print("\nThe initial array is:\n", arr1)

print("The argmin() function in an array rowaxes:\n", np.argmin(arr1, axis=0))
print("The argmin() function in an array colaxes:\n", np.argmin(arr1, axis=1))

print("The argmax() function in an array rowaxes:\n", np.argmax(arr1, axis=0))
print("The argmax() function in an array colaxes:\n", np.argmax(arr1, axis=1))


The initial array is:
 [[0.64613613 0.76164194 0.99018613 0.37535113 0.55263762]
 [0.31597277 0.00746557 0.0538908  0.75470474 0.7414404 ]
 [0.51909132 0.88040038 0.4401489  0.13677483 0.51288027]
 [0.15205435 0.68332007 0.43642789 0.93096855 0.95071686]
 [0.90792892 0.50683742 0.0694097  0.927125   0.26496601]]
The argmin() function in an array rowaxes:
 [3 1 1 2 4]
The argmin() function in an array colaxes:
 [3 1 3 0 2]
The argmax() function in an array rowaxes:
 [4 2 0 3 3]
The argmax() function in an array colaxes:
 [2 3 1 4 3]


In [30]:
# numpy.ravel() returns the flatten array
# order ='C' - operating row-wise on the array will be slightly fast
print("The flatten array using numpy.ravel():\n", np.ravel(arr1, order='C'))
# order ='F' - operating col-wise on the array will be slightly fast
print("The flatten array using numpy.ravel():\n", np.ravel(arr1, order='F'))
# order ='F' - operating read/write the elements on the array will be slightly fast
print("The flatten array using numpy.ravel():\n", np.ravel(arr1, order='A'))

The flatten array using numpy.ravel():
 [0.64613613 0.76164194 0.99018613 0.37535113 0.55263762 0.31597277
 0.00746557 0.0538908  0.75470474 0.7414404  0.51909132 0.88040038
 0.4401489  0.13677483 0.51288027 0.15205435 0.68332007 0.43642789
 0.93096855 0.95071686 0.90792892 0.50683742 0.0694097  0.927125
 0.26496601]
The flatten array using numpy.ravel():
 [0.64613613 0.31597277 0.51909132 0.15205435 0.90792892 0.76164194
 0.00746557 0.88040038 0.68332007 0.50683742 0.99018613 0.0538908
 0.4401489  0.43642789 0.0694097  0.37535113 0.75470474 0.13677483
 0.93096855 0.927125   0.55263762 0.7414404  0.51288027 0.95071686
 0.26496601]
The flatten array using numpy.ravel():
 [0.64613613 0.76164194 0.99018613 0.37535113 0.55263762 0.31597277
 0.00746557 0.0538908  0.75470474 0.7414404  0.51909132 0.88040038
 0.4401489  0.13677483 0.51288027 0.15205435 0.68332007 0.43642789
 0.93096855 0.95071686 0.90792892 0.50683742 0.0694097  0.927125
 0.26496601]


In [31]:
print("New random array:", np.random.rand(5)) # 'Normal distribution, mean=0 and variance=1
print("New random array:", np.random.random(5))

New random array: [0.0505445  0.68511876 0.39337507 0.15716077 0.00332674]
New random array: [0.46711775 0.46620907 0.07138424 0.69314388 0.8177377 ]


In [32]:
import numpy as np
array = [np.nan, 4, 2, 3, 1]
# array = np.array(array).reshape(4, 3)
array2 = np.array([[np.nan,4], [1, 3]])
print("\nThe generated array:\n",array)
print("\nThe generated array:\n",array2)
print("\nThe nanargmin() in array axis =0:\n", np.nanargmin(array))
print("\nThe nanargmax() in array axis =1:\n", np.nanargmax(array))
print("\nThe nanargmin() in array axis =0:\n", np.nanargmin(array2, axis=0))
print("\nThe nanargmin() in array axis =1:\n", np.nanargmin(array2, axis=1))
print("\nThe nanargmax() in array axis =0:\n", np.nanargmax(array2, axis=0))
print("\nThe nanargmax() in array axis =1:\n", np.nanargmax(array2, axis=1))


The generated array:
 [nan, 4, 2, 3, 1]

The generated array:
 [[nan  4.]
 [ 1.  3.]]

The nanargmin() in array axis =0:
 4

The nanargmax() in array axis =1:
 1

The nanargmin() in array axis =0:
 [1 1]

The nanargmin() in array axis =1:
 [1 0]

The nanargmax() in array axis =0:
 [1 0]

The nanargmax() in array axis =1:
 [1 1]


In [33]:
# np.isinf()
print("The np.isinf():", np.isinf(np.inf))
print("The np.isinf():", np.isinf(np.NINF))
print("The np.isinf():", np.isinf(1))

The np.isinf(): True
The np.isinf(): True
The np.isinf(): False


In [34]:
array = np.arange(40).reshape(4, 2, 5) 
print("New array:\n", array)
print("Flattening the array:\n", array.flat[2:8])
print("Flattening the array:\n", array.flat[0:12])

New array:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]]
Flattening the array:
 [2 3 4 5 6 7]
Flattening the array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [35]:
# numpy.isrealobj() - function which used to identify the element in an array is complex or real?
print("numpy.isrealobj():\n", np.isrealobj(array))

new_array = np.arange(20, dtype=complex).reshape(4, 5)
print("The new generated array:", new_array)
print("Check whether the array element has real or complex element:\n", np.isrealobj(new_array))
print("Check whether the array element has real or complex element:\n", np.iscomplexobj(new_array))

numpy.isrealobj():
 True
The new generated array: [[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j]
 [ 5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j]
 [10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j]
 [15.+0.j 16.+0.j 17.+0.j 18.+0.j 19.+0.j]]
Check whether the array element has real or complex element:
 False
Check whether the array element has real or complex element:
 True


In [36]:
# numpy.expm1 - a mathematical function helps user to calculate exponential of all elements subtracting 1 from all the input array elements
array = np.array([1, 2, 3, 1, 2])
print("The numpy.expm1():\n", np.expm1(array))

The numpy.expm1():
 [ 1.71828183  6.3890561  19.08553692  1.71828183  6.3890561 ]


In [37]:
array = np.random.random(20).reshape(4, 5)
print("\nThe generated array:\n", array )
print("numpy.amax() find the max of all array elements:\n", np.amax(array, axis=0))
print("numpy.amax() find the min of all array elements:\n", np.amin(array, axis=0))
print("numpy.amax() find the max of all array elements:\n", np.amax(array, axis=1))
print("numpy.amax() find the max of all array elements:\n", np.amin(array, axis=1))


The generated array:
 [[0.38126972 0.88580956 0.68211942 0.33769166 0.65908809]
 [0.19125298 0.08127816 0.03845051 0.68164844 0.27339712]
 [0.49123114 0.90045668 0.39507272 0.30185166 0.26421628]
 [0.42026105 0.42642213 0.85054282 0.3755944  0.6830326 ]]
numpy.amax() find the max of all array elements:
 [0.49123114 0.90045668 0.85054282 0.68164844 0.6830326 ]
numpy.amax() find the min of all array elements:
 [0.19125298 0.08127816 0.03845051 0.30185166 0.26421628]
numpy.amax() find the max of all array elements:
 [0.88580956 0.68164844 0.90045668 0.85054282]
numpy.amax() find the max of all array elements:
 [0.33769166 0.03845051 0.26421628 0.3755944 ]


In [38]:
# np.isscalar(num) - returns true if type of input num is scalar
print("The number is scalar (7):\n", np.isscalar(7))
print("The number is scalar [7]:\n", np.isscalar([7]))

The number is scalar (7):
 True
The number is scalar [7]:
 False


In [39]:
# numpy.random.shuffle() - modify a sequence in-place by shuffling the elements
input_arr_1 = np.array([1, 2, 3, 1, 1, 2, 2, 1, 3, 4, 4, 1, 1, 3])
print("The input_array1:\n", input_arr_1)
np.random.shuffle(input_arr_1)
print("The randomly shuffled array:\n", input_arr_1)

The input_array1:
 [1 2 3 1 1 2 2 1 3 4 4 1 1 3]
The randomly shuffled array:
 [1 1 1 2 1 1 3 3 1 2 2 4 3 4]


In [40]:
# np.bincount(arr) - return the count of each occurenece of each elements, each bin value is the occurence of its index
input_arr_2 = np.array([1, 2, 3, 1, 1, 2, 2, 1, 3, 4, 4, 1, 1, 3])
input_arr_1 = np.array([1, 2, 3, 1, 1, 2, 2, 1, 3, 4, 4, 1, 1, 3])
np.place(input_arr_1, input_arr_1>3, [1, 22, 23])

print("\nThe input_array_1:\n", input_arr_1)
print("\nThe input_array_1:\n", input_arr_2)

print("Numpy.bincount() of array2:", np.bincount(input_arr_2))
print("Numpy.bincount() of array1:", np.bincount(input_arr_1))
print("Numpy.bincount() of both:", np.bincount(input_arr_1, input_arr_2))
# It added the occurence of elements in an array from both array


The input_array_1:
 [ 1  2  3  1  1  2  2  1  3  1 22  1  1  3]

The input_array_1:
 [1 2 3 1 1 2 2 1 3 4 4 1 1 3]
Numpy.bincount() of array2: [0 6 3 3 2]
Numpy.bincount() of array1: [0 7 3 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
Numpy.bincount() of both: [ 0. 10.  6.  9.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  4.]


In [41]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 5, 6, 7])
# np.equal(arr1, arr2)
# np.not_equal(arr1, arr2)
print("Check If this two array is equal or not:\n", np.equal(arr1, arr2))
print("Check If this two array is equal or not:\n", np.not_equal(arr1, arr2))

Check If this two array is equal or not:
 [False False False False]
Check If this two array is equal or not:
 [ True  True  True  True]


In [42]:
print("Cheking element wise array is complex or not?:\n", np.iscomplex(arr1))

Cheking element wise array is complex or not?:
 [False False False False]


In [43]:
# np.isposinf(array) -function check element wise array is +ve infinity or not
array =[np.inf, 0 , 9, 8, np.NINF]
print("Check the array is +ve inf:", np.isposinf(array))
print("Check the array is +ve inf:", np.isneginf(array))

Check the array is +ve inf: [ True False False False False]
Check the array is +ve inf: [False False False False  True]


In [44]:
array = np.random.random(10).reshape(2, 5)
print("\nThe array is:\n", array)
print("\nGetting rounding off an array element:\n", np.rint(array))


The array is:
 [[0.49033235 0.47469822 0.12394415 0.38330593 0.62708601]
 [0.23613064 0.99987497 0.80346095 0.02556525 0.57841999]]

Getting rounding off an array element:
 [[0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 1.]]


In [45]:
# numpy.insert(array, object(subarray), values, axis=None)
import numpy as np
input_arr = np.arange(12).reshape(3, 4)
print("The input array is:\n", input_arr.flatten())
np.insert(input_arr,1, -10, axis=0) # inserting -10 along axis=0 before index '1'

The input array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[  0,   1,   2,   3],
       [-10, -10, -10, -10],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [46]:
# np.delete(array,object(index), axis=NOne) - deletes the element in an array to the particula indics
np.delete(input_arr, 1, axis=0)

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [47]:
# Working with scalars
a = np.insert(input_arr, [1], [[6], [9], ], axis=0)
# inserting two sets of value 6, 9 before [1] indices row wise
print("New inserting array is:\n", a)

New inserting array is:
 [[ 0  1  2  3]
 [ 6  6  6  6]
 [ 9  9  9  9]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
print("Input_array:\n", input_arr)
a = np.insert(input_arr, [1], [[6], [9], [-10]], axis=1)
# insert [[6], [9], [-10]] before index '1' along axis=1
print("After Inserting an value along axis=1:\n", a)

Input_array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After Inserting an value along axis=1:
 [[  0   6   1   2   3]
 [  4   9   5   6   7]
 [  8 -10   9  10  11]]


In [49]:
print("The input_array:\n", input_arr)
print("The input_array inserted at axis=0:\n", np.insert(input_arr, (1, 2), 9, axis=0))
print("The input_array inserted at axis=1:\n", np.insert(input_arr, (1, 2), 9, axis=1))

The input_array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The input_array inserted at axis=0:
 [[ 0  1  2  3]
 [ 9  9  9  9]
 [ 4  5  6  7]
 [ 9  9  9  9]
 [ 8  9 10 11]]
The input_array inserted at axis=1:
 [[ 0  9  1  9  2  3]
 [ 4  9  5  9  6  7]
 [ 8  9  9  9 10 11]]


In [50]:
# numpy.append(array, values, axis=None)
print("The input_array:\n", input_arr)
print("The appended array:\n", np.append(input_arr, input_arr, axis=1))

The input_array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The appended array:
 [[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [51]:
import numpy as np
input_arr_1 = np.arange(10).reshape(2, 5)
input_arr_2 = np.arange(10).reshape(2, 5)
print("Checks whether input_arr_1 is less than input_arr_2:\n", np.less(input_arr_1, input_arr_2))
print("Checks whether input_arr_1 is less and equal than input_arr_2:\n", np.less_equal(input_arr_1, input_arr_2))
print("Checks whether input_arr_1 is greater and equal than input_arr_2:\n", np.greater(input_arr_1, input_arr_2))
print("Checks whether input_arr_1 is greater and equal than input_arr_2:\n", np.greater_equal(input_arr_1, input_arr_2))

Checks whether input_arr_1 is less than input_arr_2:
 [[False False False False False]
 [False False False False False]]
Checks whether input_arr_1 is less and equal than input_arr_2:
 [[ True  True  True  True  True]
 [ True  True  True  True  True]]
Checks whether input_arr_1 is greater and equal than input_arr_2:
 [[False False False False False]
 [False False False False False]]
Checks whether input_arr_1 is greater and equal than input_arr_2:
 [[ True  True  True  True  True]
 [ True  True  True  True  True]]


In [52]:
input_arr = np.random.random(10).reshape(2, 5)
# numpy.round()
# numpy.isnan()
# numpy.iscomplexobj() -checks the each element of array is complex object
print("Input_array:\n", input_arr)
print("The round function used in numpy:\n", np.round(input_arr))
print("The isnan function used in numpy:\n", np.isnan(input_arr))
print("The numpy.iscomplexobj() in numpy:\n", np.iscomplexobj(input_arr))

Input_array:
 [[0.55733716 0.72686217 0.69334551 0.84587199 0.65550499]
 [0.58393819 0.30062439 0.19060612 0.09672188 0.6196807 ]]
The round function used in numpy:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]]
The isnan function used in numpy:
 [[False False False False False]
 [False False False False False]]
The numpy.iscomplexobj() in numpy:
 False


In [53]:
print("The input array:\n", input_arr)
print("The flipped input_array:\n", np.flip(input_arr))
print("The flipped left-right input_array:\n", np.fliplr(input_arr))
print("The flipped left-right input_array:\n", np.flipud(input_arr))

The input array:
 [[0.55733716 0.72686217 0.69334551 0.84587199 0.65550499]
 [0.58393819 0.30062439 0.19060612 0.09672188 0.6196807 ]]
The flipped input_array:
 [[0.6196807  0.09672188 0.19060612 0.30062439 0.58393819]
 [0.65550499 0.84587199 0.69334551 0.72686217 0.55733716]]
The flipped left-right input_array:
 [[0.65550499 0.84587199 0.69334551 0.72686217 0.55733716]
 [0.6196807  0.09672188 0.19060612 0.30062439 0.58393819]]
The flipped left-right input_array:
 [[0.58393819 0.30062439 0.19060612 0.09672188 0.6196807 ]
 [0.55733716 0.72686217 0.69334551 0.84587199 0.65550499]]


In [54]:
input_arr = np.random.random(16).reshape(4, 4)
print("The input_array is:\n", input_arr)
print("The new array with upper diagonal triangle:\n", np.triu(input_arr))
print("The new array with lower diagonal triangle:\n", np.tril(input_arr))


The input_array is:
 [[0.94090346 0.36687079 0.02921369 0.35380658]
 [0.08982201 0.3994864  0.57525368 0.61346773]
 [0.44010736 0.75161089 0.5182795  0.54907063]
 [0.09605386 0.66671946 0.64275908 0.31369725]]
The new array with upper diagonal triangle:
 [[0.94090346 0.36687079 0.02921369 0.35380658]
 [0.         0.3994864  0.57525368 0.61346773]
 [0.         0.         0.5182795  0.54907063]
 [0.         0.         0.         0.31369725]]
The new array with lower diagonal triangle:
 [[0.94090346 0.         0.         0.        ]
 [0.08982201 0.3994864  0.         0.        ]
 [0.44010736 0.75161089 0.5182795  0.        ]
 [0.09605386 0.66671946 0.64275908 0.31369725]]


In [55]:
# numpy.tri(no_rows, no_cols, k=0/1/-1)
print("\nThe diagonal matrix with K=0:\n", np.tri(4, 4, k= 0))
print("\nThe diagonal matrix with K=0:\n", np.tri(4, 4, k=1))
print("\nThe diagonal matrix with K=0:\n", np.tri(4, 4, k=-1))


The diagonal matrix with K=0:
 [[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]

The diagonal matrix with K=0:
 [[1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

The diagonal matrix with K=0:
 [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]]


In [56]:
# numpy.prod(input_arr)-calculates the product of each element in an array along the axes
print("The input_array is:\n", input_arr)
print("The numpy.prod() is:", np.prod(input_arr, axis=0))
print("The numpy.prod() is:", np.prod(input_arr, axis=1))

The input_array is:
 [[0.94090346 0.36687079 0.02921369 0.35380658]
 [0.08982201 0.3994864  0.57525368 0.61346773]
 [0.44010736 0.75161089 0.5182795  0.54907063]
 [0.09605386 0.66671946 0.64275908 0.31369725]]
The numpy.prod() is: [0.00357274 0.07344315 0.00559832 0.03738493]
The numpy.prod() is: [0.00356788 0.01266298 0.09413344 0.01291269]


In [57]:
input_arr = np.arange(10).reshape(2, 5)
print("The input array is:\n", input_arr)

print("The square of each element in an array:\n", np.square(input_arr))
print("The exponential of each element in an array:\n", np.exp(input_arr))
print("The 2**x of each element in an array:\n", np.exp2(input_arr))

The input array is:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
The square of each element in an array:
 [[ 0  1  4  9 16]
 [25 36 49 64 81]]
The exponential of each element in an array:
 [[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
  5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
  8.10308393e+03]]
The 2**x of each element in an array:
 [[  1.   2.   4.   8.  16.]
 [ 32.  64. 128. 256. 512.]]


In [58]:
# numpy.cbrt(arr)
print("The cube root of each element in an array:\n", np.cbrt(input_arr))
# numpy.fix(arr) - return round of value toward 0
print("The cube root of each element in an array:\n", np.fix(input_arr))

The cube root of each element in an array:
 [[0.         1.         1.25992105 1.44224957 1.58740105]
 [1.70997595 1.81712059 1.91293118 2.         2.08008382]]
The cube root of each element in an array:
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [59]:
# numpy.empty() - generates the array of size(2,4) with random numbers
print(np.empty([2, 4], dtype=int))

prev_arr = np.arange(12).reshape(3, 4)
print("\nThe previous array is:\n", prev_arr)
print("\nThe empty_like() new array is:\n", np.empty_like(prev_arr))

print("\nThe ones() new array is:\n", np.ones((2, 3), dtype=float))
print("\nThe ones_like() new array is:\n", np.ones_like(prev_arr))

print("\nThe full_like() new array is:\n", np.full_like(prev_arr, -10.0))

[[  179617894  1064122980  1369509747  1066004236]
 [  504023941  1069029665 -2040798100  1066037752]]

The previous array is:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

The empty_like() new array is:
 [[         0 1072693248          0 1072693248]
 [         0 1072693248          0 1072693248]
 [         0 1072693248          0 1072693248]]

The ones() new array is:
 [[1. 1. 1.]
 [1. 1. 1.]]

The ones_like() new array is:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

The full_like() new array is:
 [[-10 -10 -10 -10]
 [-10 -10 -10 -10]
 [-10 -10 -10 -10]]


In [60]:
# numpy.absolute(arr)
print("The absolute value from array:\n", np.absolute(prev_arr))

The absolute value from array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [61]:
arr1 = np.arange(4, dtype=float)
arr2 = np.arange(4, dtype=float) + 12

print("\nThe array_1 is:\n", arr1)
print("\nThe array_2 is:\n", arr2)

print("The hypotenuse of of any arr1(length) and arr2(perpendiculat):\n", np.hypot(arr1, arr2))


The array_1 is:
 [0. 1. 2. 3.]

The array_2 is:
 [12. 13. 14. 15.]
The hypotenuse of of any arr1(length) and arr2(perpendiculat):
 [12.         13.03840481 14.14213562 15.29705854]


In [62]:
arr1 = np.random.rand(10).reshape(2, 5)
arr2 = np.random.random(10).reshape(2, 5)
print("\nThe arr1:\n", arr1)
print("\nThe arr2:\n", arr2)
print("The array_equal():", np.array_equal(arr1, arr2))
print("The array_equiv():", np.array_equiv(arr1, arr2))

print("The array_equiv():", np.array_equiv(arr1, arr2))


The arr1:
 [[0.3821516  0.45401805 0.75065132 0.08258827 0.34411129]
 [0.34861264 0.21286626 0.67916266 0.38057783 0.3112798 ]]

The arr2:
 [[0.98594378 0.38961469 0.27639465 0.18416763 0.15366904]
 [0.07566083 0.78595938 0.95922191 0.72220361 0.70423634]]
The array_equal(): False
The array_equiv(): False
The array_equiv(): False


In [63]:
print("\nThe logical_and:\n", np.logical_and(arr1, arr2))
print("\nThe logical_or:\n", np.logical_or(arr1, arr2))
print("\nThe logical_xor:\n", np.logical_xor(arr1, arr2))
print("\nThe logical_not:\n", np.logical_xor(arr1, arr2))


The logical_and:
 [[ True  True  True  True  True]
 [ True  True  True  True  True]]

The logical_or:
 [[ True  True  True  True  True]
 [ True  True  True  True  True]]

The logical_xor:
 [[False False False False False]
 [False False False False False]]

The logical_not:
 [[False False False False False]
 [False False False False False]]


In [64]:
# numpy.degree()
print("\nThe numpy.degree():", np.degrees(arr1))
# numpy.radian()
print("\nThe numpy.radians():", np.radians(arr1))

# numpy.arcsin() - calculates the inverse of sin()
print("\nThe numpy.sin():", np.sin(arr1))
print("\nThe numpy.cos():", np.cos(arr1))
print("\nThe numpy.arcsin():", np.arcsin(arr1))
print("\nThe numpy.arccos():", np.arccos(arr1))


The numpy.degree(): [[21.89567388 26.01331827 43.00915259  4.73195921 19.71612456]
 [19.97403283 12.19633808 38.91315392 21.80550348 17.83501859]]

The numpy.radians(): [[0.0066698  0.00792411 0.01310134 0.00144144 0.00600587]
 [0.00608444 0.00371522 0.01185362 0.00664234 0.00543286]]

The numpy.sin(): [[0.37291773 0.43858006 0.68211518 0.08249441 0.3373602 ]
 [0.34159423 0.21126233 0.62814171 0.37145702 0.30627718]]

The numpy.cos(): [[0.92786441 0.89869212 0.73124475 0.99659153 0.94137564]
 [0.93984753 0.9774294  0.77809896 0.92845015 0.95194238]]

The numpy.arcsin(): [[0.3921235  0.47126982 0.84904733 0.08268244 0.35129211]
 [0.35609047 0.21450751 0.74662122 0.39042107 0.31653944]]

The numpy.arccos(): [[1.17867283 1.0995265  0.72174899 1.48811388 1.21950422]
 [1.21470585 1.35628881 0.82417511 1.18037526 1.25425689]]


In [65]:
# numpy.diag()

print("\nThe numpy.diag():\n", np.diag(arr1))


The numpy.diag():
 [0.3821516  0.21286626]


In [66]:
# numpy.diagflat(a, k=0)
print("The numpy.diagflat():\n", np.diagflat([1, 2, 3, 4]))

# numpy.diag_indices(num)
print("The numpy.diagflat():\n", np.diag_indices(5))

print("The numpy.diagflat():\n", np.arange(16).reshape(4,4))

The numpy.diagflat():
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
The numpy.diagflat():
 (array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))
The numpy.diagflat():
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [67]:
# np.asmatrix()

input_arr = np.matrix([[2, 3, 4], [5, 6]])
print("The input_arr:", input_arr)
c = np.asmatrix(input_arr)
print("The asmatrix input_arr:\n", c)

The input_arr: [[list([2, 3, 4]) list([5, 6])]]
The asmatrix input_arr:
 [[list([2, 3, 4]) list([5, 6])]]


In [68]:
# numpy.power(arr1, arr2)-return the power(arr1, arr2) in int form
# numpy.float_power(arr1, arr2) - return the power(arr1, arr2) in float form
arr1 = np.arange(3)
arr2 = np.arange(3) + 4
print("\nThe array-1 is:\n", arr1)
print("\nThe array-2 is:\n", arr2)
print("\nThe numpy.power():\n", np.power(arr1, arr2))
print("\nThe numpy.power():\n", np.float_power(arr1, arr2))


The array-1 is:
 [0 1 2]

The array-2 is:
 [4 5 6]

The numpy.power():
 [ 0  1 64]

The numpy.power():
 [ 0.  1. 64.]


In [69]:
print("The input_arr is:\n", arr1 )
print("numpy.log():\n", np.log(arr1 + 10))
# numpy.log1p calculates the natural logaarithm value of x+1 where x belongs to all the input array elements
print("numpy.log1():\n", np.log1p(arr1 + 10))
print("numpy.log2():\n", np.log2(arr1 + 10))
print("numpy.log10():\n", np.log10(arr1 + 10))

The input_arr is:
 [0 1 2]
numpy.log():
 [2.30258509 2.39789527 2.48490665]
numpy.log1():
 [2.39789527 2.48490665 2.56494936]
numpy.log2():
 [3.32192809 3.45943162 3.5849625 ]
numpy.log10():
 [1.         1.04139269 1.07918125]


In [70]:
# numpy.eye(shape) - used to create an new array with 1 in diagonal element
# 1's in diagonal element and 0's elsewhere
# np.eye(no_of_rows, no_of_cols,k=0/1/-1 (for main diagonal, above the diagonal, and below the diagonal))
print(np.eye(2, 4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [71]:
# numpy.identity(n) -returns the identity matrix of nXn size
print(np.identity(4, dtype=float))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [77]:
# numpy.roll(array, shift-no of times to roll, axis=None)
input_arr = np.random.random(12).reshape(3, 4)
print("The input_arr:\n", input_arr)
print("\nThe numpy.roll(1 times):\n", np.roll(input_arr, 1))
print("\nThe numpy.roll(2 times):\n", np.roll(input_arr, 2))
print("\nThe numpy.roll(3 times):\n", np.roll(input_arr, 3))

The input_arr:
 [[0.68125007 0.5767297  0.78235312 0.66760805]
 [0.05233962 0.79956121 0.96149364 0.73020719]
 [0.72288276 0.69325404 0.70155875 0.81515134]]

The numpy.roll(1 times):
 [[0.81515134 0.68125007 0.5767297  0.78235312]
 [0.66760805 0.05233962 0.79956121 0.96149364]
 [0.73020719 0.72288276 0.69325404 0.70155875]]

The numpy.roll(2 times):
 [[0.70155875 0.81515134 0.68125007 0.5767297 ]
 [0.78235312 0.66760805 0.05233962 0.79956121]
 [0.96149364 0.73020719 0.72288276 0.69325404]]

The numpy.roll(3 times):
 [[0.69325404 0.70155875 0.81515134 0.68125007]
 [0.5767297  0.78235312 0.66760805 0.05233962]
 [0.79956121 0.96149364 0.73020719 0.72288276]]


In [84]:
# np.mat() - data as inteterpreed matrix
import numpy as np
A = np.mat('4, 1; 22, 1')
print("The matrix A is in mat datatype:\n", A)

B = np.mat('5, 2; 5, 2')
print("The matrix A is in mat datatype:\n", B)

C = np.mat('8, 4; 6, 6')
print("The matrix A is in mat datatype:\n", C)

a = np.bmat([[A, B], [C, A]])
print("Via bmat array like input:\n", a)

b = np.bmat('A, B; A, A')
print("Via bmat array like input:\n", b)

The matrix A is in mat datatype:
 [[ 4  1]
 [22  1]]
The matrix A is in mat datatype:
 [[5 2]
 [5 2]]
The matrix A is in mat datatype:
 [[8 4]
 [6 6]]
Via bmat array like input:
 [[ 4  1  5  2]
 [22  1  5  2]
 [ 8  4  4  1]
 [ 6  6 22  1]]
Via bmat array like input:
 [[ 4  1  5  2]
 [22  1  5  2]
 [ 4  1  4  1]
 [22  1 22  1]]
