In [101]:
import sklearn
from sklearn import datasets

In [102]:
iris = datasets.load_iris() #iris dataset
digits = datasets.load_digits() #digits dataset

In [103]:
print(digits.data) #

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [104]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [105]:
#in the case of SVM (Support vector classification)

from sklearn import svm
clf = svm.SVC(gamma = 0.001, C= 100)

In [106]:
clf.fit(digits.data[:-1], digits.target[:-1])  # fit(X, y) is the estimator for any model that tries to learn the training data


SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [107]:
clf.predict(digits.data[-1:])

array([8])

In [108]:
#for iris dataset
from sklearn import datasets
iris = datasets.load_iris()
print(iris)

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [109]:
X =iris.data
y= iris.target

print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [110]:
clf.fit(X, y) 

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [111]:
#putting trained model in pickle
import pickle

In [112]:
s = pickle.dumps(clf) #model saved in pickle format

In [113]:
print(s)

b'\x80\x03csklearn.svm.classes\nSVC\nq\x00)\x81q\x01}q\x02(X\x08\x00\x00\x00support_q\x03cnumpy.core.multiarray\n_reconstruct\nq\x04cnumpy\nndarray\nq\x05K\x00\x85q\x06C\x01bq\x07\x87q\x08Rq\t(K\x01K0\x85q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i4q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89C\xc0\x17\x00\x00\x00\x18\x00\x00\x00)\x00\x00\x00,\x00\x00\x002\x00\x00\x003\x00\x00\x004\x00\x00\x006\x00\x00\x007\x00\x00\x008\x00\x00\x009\x00\x00\x00?\x00\x00\x00B\x00\x00\x00D\x00\x00\x00F\x00\x00\x00H\x00\x00\x00I\x00\x00\x00L\x00\x00\x00M\x00\x00\x00N\x00\x00\x00S\x00\x00\x00T\x00\x00\x00U\x00\x00\x00V\x00\x00\x00W\x00\x00\x00[\x00\x00\x00]\x00\x00\x00b\x00\x00\x00e\x00\x00\x00j\x00\x00\x00n\x00\x00\x00o\x00\x00\x00q\x00\x00\x00w\x00\x00\x00y\x00\x00\x00{\x00\x00\x00~\x00\x00\x00\x7f\x00\x00\x00\x81\x00\x00\x00\x85\x00\x00\x00\x86\x00\x00\x00\x89\x00\x00\x00\x8a\x00\x00\x00\x8d\x00\x00\x00\x8e\x00\x00\x00\x92\x00\x00\x00\x93\x00

In [114]:
clf2 = pickle.loads(s)
print(clf2)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [115]:
clf2.predict (X[0:1])  #predict function in sklearn is for predicting unseen data from the model that has trained using the training data

array([0])

# Type casting
fit_transform(X)  is the function which used for transforming the type of one data type to another data type

In [116]:
import numpy as np
from sklearn import random_projection

In [117]:
rng = np.random.RandomState(0)
print(rng)

RandomState(MT19937)


In [118]:
X = rng.rand(10, 2000)
print(X)

[[0.5488135  0.71518937 0.60276338 ... 0.48010781 0.64386404 0.50177313]
 [0.81151847 0.47608399 0.52315599 ... 0.83000295 0.93280618 0.30833843]
 [0.29264205 0.56651827 0.13741443 ... 0.69652287 0.48369661 0.33955073]
 ...
 [0.32059506 0.24986687 0.03107279 ... 0.38938909 0.93272    0.33276632]
 [0.39553738 0.84401749 0.15044175 ... 0.53561083 0.35458205 0.93578099]
 [0.8140271  0.85133715 0.43113659 ... 0.44645576 0.36012661 0.62588665]]


In [119]:
X.dtype

dtype('float64')

The sklearn.random_projection.GaussianRandomProjection reduces the dimensionality by projecting the original input space on a randomly generated matrix where components are drawn from the gaussian distribution .

In [120]:
X=np.array(X, dtype = 'float32')
X.dtype

dtype('float32')

In [121]:
transformer = random_projection.GaussianRandomProjection()
X_new = transformer.fit_transform(X)
print("Dtype of X:", X_new.dtype)
print("Shape of X:", X_new.shape) 


Dtype of X: float64
Shape of X: (10, 1973)


Refitting the parameters in sklearn


In [122]:
from sklearn import datasets
from sklearn.svm import SVC #support vector classification
X, y = datasets.load_iris(return_X_y = True) #X : input, targets
cls = SVC()
cls.fit(X, y)

c:\users\uib43225\pycharmprojects\fusion\racam\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [123]:
#ssetting the parameters kernel and max_iter
cls.set_params(kernel ='linear', max_iter=10).fit(X, y)

c:\users\uib43225\pycharmprojects\fusion\racam\lib\site-packages\sklearn\svm\base.py:241: ConvergenceWarning: Solver terminated early (max_iter=10).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=10, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [124]:
cls.predict(X[0:5])

array([0, 0, 0, 0, 0])

In [125]:
#new parameter
cls.set_params(kernel= 'rbf', gamma='scale').fit(X, y)

c:\users\uib43225\pycharmprojects\fusion\racam\lib\site-packages\sklearn\svm\base.py:241: ConvergenceWarning: Solver terminated early (max_iter=10).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=10, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [126]:
cls.predict(X[0:5])

array([0, 0, 0, 0, 0])

Multiclass and Multifitting

In [127]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
#Also known as one-vs-all, this strategy consists in fitting one classifier per class
from sklearn.preprocessing import LabelBinarizer

In [128]:
X = [[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]
y = [0, 0, 1, 1, 2]

In [129]:
classif = OneVsRestClassifier(estimator=SVC (gamma='scale', random_state=0))

In [130]:
classif

OneVsRestClassifier(estimator=SVC(C=1.0, cache_size=200, class_weight=None,
                                  coef0=0.0, decision_function_shape='ovr',
                                  degree=3, gamma='scale', kernel='rbf',
                                  max_iter=-1, probability=False,
                                  random_state=0, shrinking=True, tol=0.001,
                                  verbose=False),
                    n_jobs=None)

In [131]:
classif.fit(X, y)

OneVsRestClassifier(estimator=SVC(C=1.0, cache_size=200, class_weight=None,
                                  coef0=0.0, decision_function_shape='ovr',
                                  degree=3, gamma='scale', kernel='rbf',
                                  max_iter=-1, probability=False,
                                  random_state=0, shrinking=True, tol=0.001,
                                  verbose=False),
                    n_jobs=None)

In [132]:
classif.predict(X)

array([0, 0, 1, 1, 2])

In [133]:
y = LabelBinarizer().fit_transform(y)
# fit_transform(self, y)	Fit label binarizer and transform multi-class labels to binary labels.
# inverse_transform(self, Y[, threshold])	Transform binary labels back to multi-class labels

In [134]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [135]:
classif.fit(X, y).predict(X)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [136]:
#Multilabel Binarizer
from sklearn.preprocessing import MultiLabelBinarizer
y = [[0, 1], [0, 2], [1, 3], [0, 2, 3], [2, 4]]
y = MultiLabelBinarizer().fit_transform(y)

In [137]:
y

array([[1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 1, 0],
       [0, 0, 1, 0, 1]])

In [138]:
classif.fit(X, y).predict(X)

array([[1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0]])